# Generated by Django 5.0.1 on 2024-01-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0002_rename_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Price',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_lib.book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_lib.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='books_ordered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_ordered_by_cart', to='core_lib.cartitem'),
        ),
    ]
