# Generated by Django 5.0.1 on 2024-01-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0003_remove_book_price_book_quantity_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
    ]
