# Generated by Django 5.0.1 on 2024-01-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0004_remove_cart_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='books_ordered',
            new_name='books',
        ),
    ]
