# Generated by Django 5.0.1 on 2024-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0005_rename_books_ordered_cart_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(through='core_lib.CartItem', to='core_lib.book'),
        ),
    ]
