# Generated by Django 5.0.1 on 2024-01-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0006_remove_cart_books_cart_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rented_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
