# Generated by Django 5.0.1 on 2024-01-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0007_book_rented_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rented_time',
        ),
    ]
