# Generated by Django 5.0.1 on 2024-01-31 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0008_remove_book_rented_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='rental_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='return_date',
        ),
        migrations.AddField(
            model_name='book',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 10, 54, 41, 95486)),
        ),
        migrations.AddField(
            model_name='book',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
