# Generated by Django 5.0.1 on 2024-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0009_remove_cart_rental_date_remove_cart_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
