# Generated by Django 5.0.1 on 2024-01-31 11:00

import core_lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0010_alter_book_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.DateTimeField(default=core_lib.models.get_default_due_date),
        ),
    ]
