# Generated by Django 5.0.1 on 2024-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0014_recenzie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='Nume', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('subiect', models.CharField(default='Subiect', max_length=255)),
                ('mesaj', models.TextField(default='Mesajul tau', max_length=1000)),
            ],
        ),
    ]
