# Generated by Django 5.0.1 on 2024-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0016_alter_contact_email_alter_contact_mesaj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='liked_books',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rented',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rented_books',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
