# Generated by Django 5.0.1 on 2024-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0017_contact_liked_books_contact_rented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='rented',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
