# Generated by Django 5.0.1 on 2024-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lib', '0018_alter_contact_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
